Repository ES2-UFPI/Unichat, pull requests merged in 2019-04, with the labels that each got.

#19 Criado o componente mensagem referente ao issue #6
  android/app/build.gradle
  android/app/src/main/java/com/unichat/MainApplication.java
  android/settings.gradle
  ios/Unichat.xcodeproj/project.pbxproj
  package-lock.json
  package.json
  src/Components/mensagem.js
Labels: needs review

#20 Done firebase configuration on both android and ios
  .gitignore
  android/app/build.gradle
  android/app/google-services.json
  android/app/src/main/java/com/unichat/MainApplication.java
  android/build.gradle
  android/settings.gradle
  ios/GoogleService-Info.plist
  ios/Podfile
  ios/Podfile.lock
  ios/Unichat.xcodeproj/project.pbxproj
  ios/Unichat.xcworkspace/contents.xcworkspacedata
  ios/Unichat.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  ios/Unichat/AppDelegate.m
  ios/Unichat/Info.plist
  package-lock.json
  package.json
  yarn.lock
Labels: needs review

#21 Chat Screen done
  .eslintrc.json
  App.js
  android/app/build.gradle
  android/app/src/main/assets/fonts/AntDesign.ttf
  android/app/src/main/assets/fonts/Entypo.ttf
  android/app/src/main/assets/fonts/EvilIcons.ttf
  android/app/src/main/assets/fonts/Feather.ttf
  android/app/src/main/assets/fonts/FontAwesome.ttf
  android/app/src/main/assets/fonts/FontAwesome5_Brands.ttf
  android/app/src/main/assets/fonts/FontAwesome5_Regular.ttf
  android/app/src/main/assets/fonts/FontAwesome5_Solid.ttf
  android/app/src/main/assets/fonts/Foundation.ttf
  android/app/src/main/assets/fonts/Ionicons.ttf
  android/app/src/main/assets/fonts/MaterialCommunityIcons.ttf
  android/app/src/main/assets/fonts/MaterialIcons.ttf
  android/app/src/main/assets/fonts/Octicons.ttf
  android/app/src/main/assets/fonts/SimpleLineIcons.ttf
  android/app/src/main/assets/fonts/Zocial.ttf
  android/app/src/main/java/com/unichat/MainApplication.java
  android/settings.gradle
  ios/Unichat.xcodeproj/project.pbxproj
  ios/Unichat/Info.plist
  package-lock.json
  package.json
  src/Components/MessageInput.js
  src/Components/mensagem.js
  src/Screens/Conversas/conversas.js
  yarn.lock
Labels: needs review

#26 Store message#9
  android/app/build.gradle
  android/app/src/main/java/com/unichat/MainApplication.java
  ios/Unichat.xcodeproj/project.pbxproj
  ios/Unichat/Info.plist
  src/Components/MessageInput.js
  src/Screens/Conversas/conversas.js
Labels: PR: reviewed-approved, needs review

#28 Implementação da recuperação de mensagens do servidor #10
  package-lock.json
  src/Screens/Conversas/conversas.js
Labels: PR: reviewed-approved, needs review

#30 adding Open Sans fonts
  android/app/src/main/assets/fonts/Dokdo.ttf
  android/app/src/main/assets/fonts/OpenSans-Bold.ttf
  android/app/src/main/assets/fonts/OpenSans-BoldItalic.ttf
  android/app/src/main/assets/fonts/OpenSans-ExtraBold.ttf
  android/app/src/main/assets/fonts/OpenSans-ExtraBoldItalic.ttf
  android/app/src/main/assets/fonts/OpenSans-Italic.ttf
  android/app/src/main/assets/fonts/OpenSans-Light.ttf
  android/app/src/main/assets/fonts/OpenSans-LightItalic.ttf
  android/app/src/main/assets/fonts/OpenSans-SemiBold.ttf
  android/app/src/main/assets/fonts/OpenSans-SemiBoldItalic.ttf
  android/app/src/main/assets/fonts/OpenSans.ttf
  ios/Unichat.xcodeproj/project.pbxproj
  ios/Unichat/Info.plist
  package.json
  src/assets/fonts/Dokdo.ttf
  src/assets/fonts/OpenSans-Bold.ttf
  src/assets/fonts/OpenSans-BoldItalic.ttf
  src/assets/fonts/OpenSans-ExtraBold.ttf
  src/assets/fonts/OpenSans-ExtraBoldItalic.ttf
  src/assets/fonts/OpenSans-Italic.ttf
  src/assets/fonts/OpenSans-Light.ttf
  src/assets/fonts/OpenSans-LightItalic.ttf
  src/assets/fonts/OpenSans-SemiBold.ttf
  src/assets/fonts/OpenSans-SemiBoldItalic.ttf
  src/assets/fonts/OpenSans.ttf
Labels: PR: unreviewed

#31 Criada tela de verificação #16
  android/app/build.gradle
  android/app/src/main/java/com/unichat/MainApplication.java
  android/settings.gradle
  ios/Podfile
  package-lock.json
  package.json
  src/Screens/Verification/verification.js
Labels: PR: reviewed-approved

#32 Auth screen#14
  android/app/build.gradle
  android/app/src/main/java/com/unichat/MainApplication.java
  android/settings.gradle
  ios/Unichat.xcodeproj/project.pbxproj
  package.json
  src/Screens/Auth/auth.js
  src/routes.js
  yarn.lock
Labels: PR: reviewed-approved, needs review

#35 React navigation#22
  src/Screens/Auth/auth.js
  src/Screens/Verification/verification.js
  src/routes.js
Labels: PR: reviewed-approved, needs review

#37 Mensagens agora aparecem na ordem correta #34
  src/Screens/Conversas/conversas.js
Labels: fix

#39 sendMessage #34
  src/Screens/Auth/auth.js
  src/Screens/Conversas/conversas.js
  src/Screens/Verification/verification.js
Labels: PR: reviewed-approved

#41 Neto#refactoring
  .eslintrc.json
  src/Components/Chat/chatContainer.js
  src/Components/Chat/chatHeader.js
  src/Components/Chat/chatInput.js
  src/Screens/Auth/auth.js
  src/Screens/Chat/chat.js
  src/Screens/Verification/verification.js
  src/routes.js
Labels: PR: unreviewed

#42 Tradução da mensagem
  package.json
  src/Components/Chat/chatContainer.js
  src/Screens/Chat/chat.js
  yarn.lock
Labels: PR: unreviewed

#43 Evandro#27
  package-lock.json
  src/Components/Chat/chatInput.js
Labels: PR: reviewed-approved

#45 Update README.md
  README.md
Labels: PR: unreviewed

#46 Re-enviando a refatoração da Auth devidamente atualizada
  package.json
  src/Screens/Auth/auth.js
  src/assets/country_dials/dials.json
  yarn.lock
Labels: PR: reviewed-approved, needs review

#60 Bug Fix: Empty message
  src/Components/Chat/chatInput.js
  src/Screens/Auth/auth.js
  src/Screens/Chat/chat.js
Labels: PR: reviewed-approved, needs review

#62 Fix a bug in render method [auth.js]
  src/Screens/Auth/auth.js
Labels: PR: reviewed-approved, needs review

#63 Setup Travis CI
  .travis.yml
  __tests__/App-test.js
  package-lock.json
  package.json
Labels: PR: reviewed-approved, needs review

#64 Refatoramento
  src/Screens/Auth/auth.js
  src/Screens/Chat/chat.js
  src/Screens/Verification/verification.js
Labels: PR: reviewed-approved

#65 Contacts screen#48
  src/Components/Contacts/contactHeader.js
  src/Screens/Contacts/contacts.js
  src/routes.js
Labels: PR: reviewed-approved, needs review

#68 Adicionada a versão correta do Flow no projeto.
  .flowconfig
Labels: PR: reviewed-approved, needs review

#70 Neto#navigation
  src/Screens/Chat/chat.js
  src/routes.js
Labels: PR: reviewed-approved, needs review
