Repository ES2-UFPI/Unichat, pull requests merged in 2019-06, with the labels that each got.

#184 Create PRIVACY-POLICY.md
  PRIVACY-POLICY.md
Labels: PR: reviewed-approved

#183 update axios package
  package-lock.json
  package.json
Labels: PR: unreviewed

#171 Max#ver idioma original
  src/Components/Chat/chatContainer.js
  src/Components/mensagem.js
  src/Screens/Chat/chat.js
Labels: PR: reviewed-approved

#174 Adicionada função de dar share do aplicativo para os amigos :)
  src/Components/Config/configBody.js
Labels: PR: unreviewed, needs review

#177 Idiomas - LanguagesHeader
  src/Components/Languages/languagesHeader.js
  src/Screens/Languages/languages.js
  src/routes.js
Labels: PR: unreviewed, needs review

#187 Políticas de Privacidade
  src/Components/Config/configBody.js
Labels: PR: unreviewed, needs review

#172 Max#componente para grupo
  src/Components/Chat/chatContainer.js
  src/Components/mensagem.js
  src/functions/getColor.js
Labels: PR: unreviewed, needs review

#186 Fix bug 142 and refactor routes
  functions/index.js
  src/index.js
  src/routes.js
Labels: PR: reviewed-approved

#169 notification enabled/disabled option
  functions/index.js
  src/Components/Config/configBody.js
  src/Screens/PerfilSettings/perfilsettings.js
Labels: PR: reviewed-approved

#170 Set orientation to portrait only
  android/app/src/main/AndroidManifest.xml
Labels: PR: reviewed-approved

#185 Jpe#about screen
  src/Components/About/aboutCards.js
  src/Components/About/aboutHeader.js
  src/Components/Config/configBody.js
  src/Screens/About/about.js
  src/assets/imgs/dev_profiles/evandro.jpeg
  src/assets/imgs/dev_profiles/jpe.jpeg
  src/assets/imgs/dev_profiles/max.jpeg
  src/assets/imgs/dev_profiles/neto.jpeg
  src/assets/imgs/unichat-icon.png
  src/routes.js
Labels: PR: reviewed-approved, needs review

#173 Max#limitar imagem
  src/Components/mensagem.js
  src/Screens/EditPerfil/editperfil.js
  src/Screens/PerfilSettings/perfilsettings.js
Labels: PR: unreviewed, needs review

#175 Adicionada foto padrão caso o usuário não escolha
  src/Screens/PerfilSettings/perfilsettings.js
Labels: PR: unreviewed, needs review

#180 Set icon app, create splash screen and more...
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/unichat/MainActivity.java
  android/app/src/main/res/drawable-hdpi/icon.png
  android/app/src/main/res/drawable-hdpi/logo_notification.png
  android/app/src/main/res/drawable-ldpi/icon.png
  android/app/src/main/res/drawable-mdpi/icon.png
  android/app/src/main/res/drawable-mdpi/logo_notification.png
  android/app/src/main/res/drawable-xhdpi/icon.png
  android/app/src/main/res/drawable-xhdpi/logo_notification.png
  android/app/src/main/res/drawable-xxhdpi/icon.png
  android/app/src/main/res/drawable-xxhdpi/logo_notification.png
  android/app/src/main/res/drawable-xxxhdpi/icon.png
  android/app/src/main/res/drawable-xxxhdpi/logo_notification.png
  android/app/src/main/res/drawable/background_splash.xml
  android/app/src/main/res/drawable/icon.png
  android/app/src/main/res/drawable/logo.png
  android/app/src/main/res/drawable/logo_notification.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/styles.xml
  functions/index.js
  src/Screens/Conversas/conversas.js
Labels: PR: reviewed-approved

#192 Adicionados requisitos para implementação de testes
  App.js
  __tests__/App-test.js
  jest/setup.js
  package-lock.json
  package.json
Labels: PR: reviewed-approved

#182 Max#platform touchables
  package-lock.json
  package.json
  src/Components/About/aboutHeader.js
  src/Components/Chat/chatHeader.js
  src/Components/Config/configBody.js
  src/Components/Contacts/contactHeader.js
  src/Components/Contato/contato.js
  src/Components/Conversa/conversa.js
  src/Components/Languages/languagesHeader.js
  src/Components/PreviewImage/previewImageHeader.js
  src/Components/SearchBar.js
  src/Components/mensagem.js
  src/Screens/Auth/auth.js
  src/Screens/Contacts/contacts.js
  src/Screens/Conversas/conversas.js
  src/Screens/EditPerfil/editperfil.js
  src/Screens/Languages/languages.js
  src/Screens/PerfilSettings/perfilsettings.js
  src/Screens/Verification/verification.js
Labels: PR: reviewed-approved, needs review

#200 Max#cache de mensagens
  src/Components/Chat/chatContainer.js
  src/Screens/Chat/chat.js
Labels: PR: reviewed-approved, needs review

#198 Max#feedback screen
  package-lock.json
  package.json
  src/Components/Config/configBody.js
  src/Screens/Conversas/conversas.js
  src/Screens/Feedback/feedback.js
  src/assets/imgs/unichat-icon-no-background.png
  src/routes.js
Labels: PR: unreviewed, needs review

#197 Fontes responsivas
  src/Components/About/aboutCards.js
  src/Components/About/aboutHeader.js
  src/Components/Chat/chatHeader.js
  src/Components/Chat/chatInput.js
  src/Components/Config/configBody.js
  src/Components/Config/configHeader.js
  src/Components/Contacts/contactHeader.js
  src/Components/Contato/contato.js
  src/Components/Conversa/conversa.js
  src/Components/Languages/languagesHeader.js
  src/Components/mensagem.js
  src/Components/responsive.js
  src/Screens/About/about.js
  src/Screens/Auth/auth.js
  src/Screens/Conversas/conversas.js
  src/Screens/EditPerfil/editperfil.js
  src/Screens/Languages/languages.js
  src/Screens/PerfilSettings/perfilsettings.js
  src/Screens/Verification/verification.js
Labels: PR: unreviewed, needs review

#181 Max#componente contato conversa
  src/Components/Conversa/conversa.js
Labels: PR: reviewed-approved, needs review

#205 Max#refactor verification
  src/Screens/Verification/verification.js
Labels: PR: reviewed-approved, needs review

#209 Jpe#menu chat
  package-lock.json
  package.json
  src/Components/Chat/chatHeader.js
  src/Components/Chat/chatPopUpMenu.js
  src/Screens/Chat/chat.js
Labels: PR: reviewed-approved, needs review

#208 adicionada a logo na tela de auth
  src/Screens/Auth/auth.js
Labels: PR: reviewed-approved

#202 Neto#create groups
  __mocks__/@react-native-community/async-storage.js
  __mocks__/react-native-firebase.js
  __tests__/createGroup.test.js
  functions/index.js
  jest/setup.js
  package-lock.json
  src/Components/Chat/chatContainer.js
  src/Components/Chat/chatHeader.js
  src/Components/Conversa/conversa.js
  src/Components/SearchBar.js
  src/Components/SelectContacts/header.js
  src/Screens/Chat/chat.js
  src/Screens/Conversas/conversas.js
  src/Screens/CreateGroup/CreateGroup.js
  src/Screens/GroupChat/GroupChat.js
  src/Screens/SelectContacts/SelectContacts.js
  src/index.js
  src/routes.js
  yarn.lock
Labels: PR: unreviewed

#201 Implementado teste da tela de feedback
  __tests__/feedback.test.js
Labels: PR: reviewed-approved

#211 Criado teste para tela de Sobre
  __tests__/aboutScreen.test.js
Labels: PR: reviewed-approved, needs review

#210 Correção na recuperação de mensagens ao dar scroll
  src/Screens/Chat/chat.js
Labels: PR: reviewed-approved

#207 trocado a cor dos ícones da tela editperfil
  src/Components/About/aboutHeader.js
  src/Components/Chat/chatHeader.js
  src/Components/Chat/chatInput.js
  src/Components/Contacts/contactHeader.js
  src/Components/Languages/languagesHeader.js
  src/Components/PreviewImage/previewImageHeader.js
  src/Screens/Conversas/conversas.js
  src/Screens/EditPerfil/editperfil.js
  src/Screens/Languages/languages.js
Labels: PR: reviewed-approved
