Repository ES2-UFPI/Unichat, pull requests merged in 2019-05, with the labels that each got.

#73 Max fix button sha-1
  android/app/google-services.json
  android/google-services.json
  src/Screens/Auth/auth.js
  src/Screens/Verification/verification.js
Labels: PR: reviewed-approved

#74 Evandro#47
  src/Screens/PerfilSettings/perfilsettings.js
  src/Screens/PreviewImage/previewImg.js
  src/assets/imgs/profile-placeholder.png
  src/assets/languages/languages.json
  src/routes.js
Labels: PR: unreviewed

#78 Image picker#jpe
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/unichat/MainApplication.java
  android/settings.gradle
  ios/Podfile
  package-lock.json
  package.json
  src/Screens/Auth/auth.js
  src/Screens/PerfilSettings/perfilsettings.js
  src/Screens/Verification/verification.js
  src/assets/languages/languages.json
  yarn.lock
Labels: PR: unreviewed, needs review

#87 Refatorar da tela de contatos
  src/Components/Contacts/contactHeader.js
  src/Screens/Contacts/contacts.js
Labels: PR: unreviewed, needs review

#91 Swipe to delete -> Hold to delete
  src/Screens/Conversas/conversas.js
  yarn.lock
Labels: PR: unreviewed, needs review

#114 bugFix
  src/Screens/PerfilSettings/perfilsettings.js
Labels: PR: unreviewed

#113 Jpe#bug fix upload
  src/Screens/PerfilSettings/perfilsettings.js
Labels: PR: unreviewed, needs review

#112 tradução dinâmica
  src/Screens/Chat/chat.js
Labels: PR: reviewed-approved, needs review

#120 Fix bug in sync contacts
  src/Screens/Contacts/contacts.js
  src/Screens/Conversas/conversas.js
Labels: PR: reviewed-approved

#119 receive msg from no-contacts
  src/Screens/Auth/auth.js
  src/Screens/Chat/chat.js
  src/Screens/Contacts/contacts.js
  src/Screens/Conversas/conversas.js
Labels: PR: reviewed-approved

#115 Max#mensagens nao lidas
  src/Screens/Chat/chat.js
  src/Screens/Conversas/conversas.js
Labels: PR: unreviewed

#122 botão de enviar está no centro agora
  src/Components/Chat/chatInput.js
Labels: PR: reviewed-approved

#121 Jpe#config screen
  src/Components/Chat/chatInput.js
  src/Components/Config/configBody.js
  src/Components/Config/configHeader.js
  src/Screens/Config/config.js
  src/routes.js
Labels: PR: reviewed-approved, needs review

#123 Last Seen implementado
  android/app/build.gradle
  android/app/src/main/java/com/unichat/MainApplication.java
  android/settings.gradle
  ios/Podfile
  package-lock.json
  package.json
  src/Components/Chat/chatHeader.js
  src/Screens/Chat/chat.js
  src/Screens/Conversas/conversas.js
  src/Screens/PerfilSettings/perfilsettings.js
  src/functions/getTime.js
Labels: PR: reviewed-approved, important, needs review

#125 Neto#search conversas
  src/Components/Contacts/contactHeader.js
  src/Components/SearchBar.js
  src/Screens/Conversas/conversas.js
Labels: PR: reviewed-approved

#124 Neto#search contacts
  src/Components/Contacts/contactHeader.js
  src/Components/SearchBar.js
  src/Screens/Contacts/contacts.js
Labels: PR: reviewed-approved

#130 Bug in search contacts and conversas
  src/Screens/Contacts/contacts.js
  src/Screens/Conversas/conversas.js
Labels: PR: reviewed-approved

#132 Fixed bug 128
  src/Screens/Contacts/contacts.js
  src/Screens/Conversas/conversas.js
Labels: PR: reviewed-approved

#137 Max#refatoracao mask input
  package-lock.json
  package.json
  src/Screens/Auth/auth.js
Labels: PR: reviewed-approved, needs review

#135 Jpe#tela de idiomas
  src/Components/Chat/chatInput.js
  src/Components/Config/configBody.js
  src/Screens/Config/config.js
  src/Screens/Languages/languages.js
  src/assets/languages/languages.json
  src/routes.js
Labels: PR: unreviewed, needs review

#138 Ao clicar no nome do contato dentro da conversa é exibido um previewi…
  src/Components/Chat/chatHeader.js
  src/Screens/PerfilSettings/perfilsettings.js
  src/Screens/PreviewImage/previewImg.js
  src/routes.js
Labels: PR: reviewed-approved

#136 Alteração da forma de mostrar as mensagens melhorando o desempenho
  src/Components/Chat/chatContainer.js
  src/Components/mensagem.js
  src/Screens/Chat/chat.js
Labels: PR: reviewed-approved, needs review

#131 Max#edit perfil
  android/app/google-services.json
  android/google-services.json
  src/Components/Config/configBody.js
  src/Screens/Conversas/conversas.js
  src/Screens/EditPerfil/editperfil.js
  src/Screens/PerfilSettings/perfilsettings.js
  src/routes.js
Labels: PR: reviewed-approved, needs review

#139 Neto#push notifications
  .firebaserc
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/unichat/MainApplication.java
  firebase.json
  firestore.indexes.json
  firestore.rules
  functions/.eslintrc.json
  functions/.gitignore
  functions/index.js
  functions/package-lock.json
  functions/package.json
  package-lock.json
  package.json
  src/Screens/Conversas/conversas.js
  src/Screens/PerfilSettings/perfilsettings.js
Labels: PR: reviewed-approved

#140 Dev
  .firebaserc
  android/app/build.gradle
  android/app/google-services.json
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/unichat/MainApplication.java
  android/google-services.json
  android/settings.gradle
  firebase.json
  firestore.indexes.json
  firestore.rules
  functions/.eslintrc.json
  functions/.gitignore
  functions/index.js
  functions/package-lock.json
  functions/package.json
  ios/Podfile
  package-lock.json
  package.json
  src/Components/Chat/chatContainer.js
  src/Components/Chat/chatHeader.js
  src/Components/Chat/chatInput.js
  src/Components/Config/configBody.js
  src/Components/Config/configHeader.js
  src/Components/Contacts/contactHeader.js
  src/Components/SearchBar.js
  src/Components/mensagem.js
  src/Screens/Auth/auth.js
  src/Screens/Chat/chat.js
  src/Screens/Config/config.js
  src/Screens/Contacts/contacts.js
  src/Screens/Conversas/conversas.js
  src/Screens/EditPerfil/editperfil.js
  src/Screens/Languages/languages.js
  src/Screens/PerfilSettings/perfilsettings.js
  src/Screens/PreviewImage/previewImg.js
  src/assets/languages/languages.json
  src/functions/getTime.js
  src/routes.js
Labels: PR: unreviewed
